import type { Prisma } from '@prisma/client';
import { forbidden, notFound } from '../../lib/errors';
import { notify } from '../../lib/notify';
import { parsePage } from '../../lib/pagination';
import { prisma } from '../../lib/prisma';

export const warningsService = {
  async listForOwner(ownerId: string, query: Record<string, unknown>) {
    const { skip, take, page, pageSize } = parsePage(query);
    // Resolve tenant IDs first. MongoDB's Prisma connector can generate a $size
    // expression on null for nested list filters through Warning.tenant.
    const properties = await prisma.property.findMany({ where: { ownerId }, select: { id: true } });
    const rooms = properties.length
      ? await prisma.room.findMany({ where: { propertyId: { in: properties.map((property) => property.id) } }, select: { id: true } })
      : [];
    const [assignments, applications] = rooms.length
      ? await Promise.all([
        prisma.roomAssignment.findMany({ where: { roomId: { in: rooms.map((room) => room.id) } }, select: { tenantId: true } }),
        prisma.application.findMany({ where: { roomId: { in: rooms.map((room) => room.id) } }, select: { tenantId: true } }),
      ])
      : [[], []];
    const tenantIds = [...new Set([...assignments, ...applications].map((row) => row.tenantId))];

    // Owner sees warnings about associated tenants plus ones they issued.
    const where: Prisma.WarningWhereInput = {
      OR: [
        { issuedById: ownerId },
        ...(tenantIds.length ? [{ tenantId: { in: tenantIds } }] : []),
      ],
    };
    if (query.status) where.status = query.status as never;
    if (query.type) where.type = query.type as never;
    if (query.tenantId) where.tenantId = query.tenantId as string;

    const [items, total] = await Promise.all([
      prisma.warning.findMany({
        where,
        skip,
        take,
        orderBy: [{ status: 'asc' }, { severity: 'desc' }, { createdAt: 'desc' }],
      }),
      prisma.warning.count({ where }),
    ]);
    const visibleTenantIds = [...new Set(items.map((item) => item.tenantId).filter((id): id is string => !!id))];
    const tenants = visibleTenantIds.length
      ? await prisma.user.findMany({ where: { id: { in: visibleTenantIds } }, select: { id: true, fullName: true, email: true } })
      : [];
    const tenantsById = new Map(tenants.map((tenant) => [tenant.id, tenant]));
    return {
      items: items.map((item) => ({ ...item, tenant: item.tenantId ? tenantsById.get(item.tenantId) ?? null : null })),
      meta: { page, pageSize, total },
    };
  },

  async listForTenant(tenantId: string, query: Record<string, unknown>) {
    const { skip, take, page, pageSize } = parsePage(query);
    const where: Prisma.WarningWhereInput = { tenantId };
    if (query.status) where.status = query.status as never;
    const [items, total] = await Promise.all([
      prisma.warning.findMany({ where, skip, take, orderBy: { createdAt: 'desc' } }),
      prisma.warning.count({ where }),
    ]);
    return { items, meta: { page, pageSize, total } };
  },

  async createManual(
    ownerId: string,
    input: { tenantId: string; title: string; message: string; severity: string },
  ) {
    const tenant = await prisma.user.findUnique({ where: { id: input.tenantId } });
    if (!tenant || tenant.role !== 'TENANT') throw notFound('Tenant not found');
    // ensure the owner actually manages this tenant
    const link = await prisma.room.findFirst({
      where: {
        property: { ownerId },
        OR: [
          { assignments: { some: { tenantId: input.tenantId } } },
          { applications: { some: { tenantId: input.tenantId } } },
        ],
      },
    });
    if (!link) throw forbidden('This tenant is not associated with your properties');

    const warning = await prisma.warning.create({
      data: {
        tenantId: input.tenantId,
        issuedById: ownerId,
        type: 'MANUAL',
        severity: input.severity as never,
        title: input.title,
        message: input.message,
        autoGenerated: false,
      },
    });
    await notify({
      userId: input.tenantId,
      type: 'WARNING',
      title: `Warning: ${input.title}`,
      body: input.message,
      relatedType: 'WARNING',
      relatedId: warning.id,
    });
    return warning;
  },

  async updateStatus(userId: string, role: string, id: string, status: string) {
    const warning = await prisma.warning.findUnique({ where: { id } });
    if (!warning) throw notFound('Warning not found');
    // Tenants can acknowledge their own; owners can resolve/dismiss ones they can see.
    if (role === 'TENANT' && warning.tenantId !== userId) throw forbidden();
    if (role === 'TENANT' && !['ACKNOWLEDGED'].includes(status)) {
      throw forbidden('Tenants can only acknowledge warnings');
    }
    const data: Prisma.WarningUpdateInput = { status: status as never };
    if (status === 'ACKNOWLEDGED') data.acknowledgedAt = new Date();
    if (status === 'RESOLVED') data.resolvedAt = new Date();
    return prisma.warning.update({ where: { id }, data });
  },
};

// ---------------------------------------------------------------------------
// Automatic warning scanner
// ---------------------------------------------------------------------------

async function upsertWarning(params: {
  dedupeKey: string;
  tenantId: string | null;
  type: Prisma.WarningCreateInput['type'];
  severity: Prisma.WarningCreateInput['severity'];
  title: string;
  message: string;
  relatedType?: string;
  relatedId?: string;
}) {
  const existing = await prisma.warning.findUnique({ where: { dedupeKey: params.dedupeKey } });
  if (existing) {
    // Refresh message/severity if still active; don't spam notifications.
    if (existing.status === 'ACTIVE') {
      await prisma.warning.update({
        where: { id: existing.id },
        data: { message: params.message, severity: params.severity },
      });
    }
    return existing;
  }
  const warning = await prisma.warning.create({
    data: {
      dedupeKey: params.dedupeKey,
      tenantId: params.tenantId,
      type: params.type,
      severity: params.severity,
      title: params.title,
      message: params.message,
      relatedType: params.relatedType,
      relatedId: params.relatedId,
      autoGenerated: true,
    },
  });
  if (params.tenantId) {
    await notify({
      userId: params.tenantId,
      type: 'WARNING',
      title: `Warning: ${params.title}`,
      body: params.message,
      relatedType: 'WARNING',
      relatedId: warning.id,
    });
  }
  return warning;
}

/**
 * Scans the whole system and raises/refreshes automatic warnings for:
 * upcoming & overdue rent, repeated late payments, lease expiry, missing
 * documents, maintenance delays, cleaning delays.
 * Idempotent via dedupeKey.
 */
export async function runWarningScan(now = new Date()): Promise<{ created: number; scanned: string[] }> {
  const scanned: string[] = [];
  let created = 0;
  const countBefore = await prisma.warning.count();

  // ---- Rent: upcoming (due within 3 days) & overdue ----
  const soon = new Date(now.getTime() + 3 * 86_400_000);
  const duePayments = await prisma.payment.findMany({
    where: { status: { in: ['PENDING', 'PARTIAL', 'OVERDUE'] }, dueDate: { lte: soon } },
    include: { lease: { select: { room: { select: { name: true } } } } },
  });
  for (const p of duePayments) {
    const overdue = p.dueDate < now;
    const monthKey = `${p.periodYear}-${p.periodMonth}`;
    await upsertWarning({
      dedupeKey: `${overdue ? 'RENT_OVERDUE' : 'RENT_UPCOMING'}:${p.id}`,
      tenantId: p.tenantId,
      type: overdue ? 'RENT_OVERDUE' : 'RENT_UPCOMING',
      severity: overdue ? (p.dueDate < new Date(now.getTime() - 7 * 86_400_000) ? 'HIGH' : 'MEDIUM') : 'LOW',
      title: overdue ? 'Rent overdue' : 'Rent due soon',
      message: overdue
        ? `Rent for ${monthKey} (${p.lease.room.name}) is overdue. Outstanding: ${Number(p.totalAmount) - Number(p.amountPaid)}.`
        : `Rent for ${monthKey} (${p.lease.room.name}) is due on ${p.dueDate.toDateString()}.`,
      relatedType: 'PAYMENT',
      relatedId: p.id,
    });
  }
  scanned.push('rent');

  // ---- Repeated late payments (>=2 late in trailing 6 months) ----
  const sixMonthsAgo = new Date(now.getTime() - 182 * 86_400_000);
  const lateGroups = await prisma.payment.groupBy({
    by: ['tenantId'],
    where: { daysLate: { gt: 0 }, dueDate: { gte: sixMonthsAgo } },
    _count: { _all: true },
  });
  for (const g of lateGroups) {
    if (g._count._all >= 2) {
      await upsertWarning({
        dedupeKey: `REPEATED_LATE:${g.tenantId}:${now.getUTCFullYear()}-${now.getUTCMonth()}`,
        tenantId: g.tenantId,
        type: 'REPEATED_LATE_PAYMENT',
        severity: g._count._all >= 4 ? 'HIGH' : 'MEDIUM',
        title: 'Repeated late payments',
        message: `${g._count._all} late payments in the last 6 months.`,
      });
    }
  }
  scanned.push('repeated-late');

  // ---- Lease expiry (within 30 days) ----
  const in30 = new Date(now.getTime() + 30 * 86_400_000);
  const expiring = await prisma.lease.findMany({
    where: { status: 'ACTIVE', endDate: { lte: in30, gte: now } },
    include: { room: { select: { name: true } } },
  });
  for (const l of expiring) {
    const days = Math.ceil((l.endDate.getTime() - now.getTime()) / 86_400_000);
    await upsertWarning({
      dedupeKey: `LEASE_EXPIRY:${l.id}`,
      tenantId: l.tenantId,
      type: 'LEASE_EXPIRY',
      severity: days <= 7 ? 'HIGH' : days <= 14 ? 'MEDIUM' : 'LOW',
      title: 'Lease expiring soon',
      message: `Lease for ${l.room.name} expires in ${days} day(s) on ${l.endDate.toDateString()}.`,
      relatedType: 'LEASE',
      relatedId: l.id,
    });
  }
  // Expire past-due leases
  await prisma.lease.updateMany({
    where: { status: 'ACTIVE', endDate: { lt: now } },
    data: { status: 'EXPIRED' },
  });
  scanned.push('lease-expiry');

  // ---- Missing documents (application stuck in DOCS_PENDING > 3 days) ----
  const threeDaysAgo = new Date(now.getTime() - 3 * 86_400_000);
  const stuck = await prisma.application.findMany({
    where: { status: 'DOCS_PENDING', createdAt: { lt: threeDaysAgo } },
    include: { room: { select: { name: true } }, documents: { select: { type: true } } },
  });
  const REQUIRED = ['ID_PROOF', 'ADDRESS_PROOF', 'INCOME_PROOF'];
  for (const a of stuck) {
    const have = new Set(a.documents.map((d) => d.type));
    const missing = REQUIRED.filter((r) => !have.has(r as never));
    if (missing.length > 0) {
      await upsertWarning({
        dedupeKey: `MISSING_DOCS:${a.id}`,
        tenantId: a.tenantId,
        type: 'MISSING_DOCUMENTS',
        severity: 'MEDIUM',
        title: 'Missing application documents',
        message: `Application for ${a.room.name} is missing: ${missing.join(', ')}.`,
        relatedType: 'APPLICATION',
        relatedId: a.id,
      });
    }
  }
  scanned.push('missing-docs');

  // ---- Maintenance delays (URGENT/HIGH open > 2 days, others > 7 days) ----
  const openMaint = await prisma.maintenanceRequest.findMany({
    where: { status: { in: ['OPEN', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD'] } },
    include: { room: { select: { name: true, property: { select: { ownerId: true } } } } },
  });
  for (const m of openMaint) {
    const ageDays = (now.getTime() - m.createdAt.getTime()) / 86_400_000;
    const threshold = m.priority === 'URGENT' || m.priority === 'HIGH' ? 2 : 7;
    if (ageDays > threshold) {
      await upsertWarning({
        dedupeKey: `MAINT_DELAY:${m.id}`,
        tenantId: m.tenantId,
        type: 'MAINTENANCE_DELAY',
        severity: m.priority === 'URGENT' ? 'CRITICAL' : m.priority === 'HIGH' ? 'HIGH' : 'MEDIUM',
        title: 'Maintenance request delayed',
        message: `"${m.title}" (${m.priority}) for ${m.room.name} has been open ${Math.floor(ageDays)} days.`,
        relatedType: 'MAINTENANCE',
        relatedId: m.id,
      });
    }
  }
  scanned.push('maintenance-delay');

  // ---- Cleaning delays (scheduled in the past, not completed) ----
  const overdueCleaning = await prisma.cleaningTask.findMany({
    where: { status: { in: ['SCHEDULED', 'ASSIGNED', 'IN_PROGRESS'] }, scheduledFor: { lt: now } },
    include: { property: { select: { name: true } } },
  });
  for (const c of overdueCleaning) {
    const lateDays = Math.floor((now.getTime() - c.scheduledFor.getTime()) / 86_400_000);
    await upsertWarning({
      dedupeKey: `CLEAN_DELAY:${c.id}`,
      tenantId: null,
      type: 'CLEANING_DELAY',
      severity: lateDays >= 3 ? 'HIGH' : 'MEDIUM',
      title: 'Cleaning task overdue',
      message: `"${c.title}" at ${c.property.name} was scheduled ${lateDays} day(s) ago and is not complete.`,
      relatedType: 'CLEANING',
      relatedId: c.id,
    });
    if (c.status !== 'MISSED' && lateDays >= 2) {
      await prisma.cleaningTask.update({ where: { id: c.id }, data: { status: 'MISSED' } });
    }
  }
  scanned.push('cleaning-delay');

  // ---- Auto-resolve rent warnings whose payment is now settled ----
  await prisma.warning.updateMany({
    where: {
      status: 'ACTIVE',
      type: { in: ['RENT_UPCOMING', 'RENT_OVERDUE'] },
      relatedType: 'PAYMENT',
      relatedId: {
        in: (
          await prisma.payment.findMany({ where: { status: { in: ['PAID', 'WAIVED'] } }, select: { id: true } })
        ).map((p) => p.id),
      },
    },
    data: { status: 'RESOLVED', resolvedAt: now },
  });

  const countAfter = await prisma.warning.count();
  created = Math.max(0, countAfter - countBefore);
  return { created, scanned };
}
