import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api, apiErrorMessage } from '../../lib/api';
import { Icon } from '../../components/Icon';
import {
  Badge,
  EmptyState,
  ErrorBanner,
  PageHeader,
  RailFilters,
  RailStats,
  Spinner,
  SplitLayout,
  date,
} from '../../components/ui';

interface Warning {
  id: string;
  type: string;
  severity: string;
  status: string;
  title: string;
  message: string;
  autoGenerated: boolean;
  createdAt: string;
  tenant: { fullName: string } | null;
}

type Filter = 'ACTIVE' | 'ACKNOWLEDGED' | 'RESOLVED' | 'DISMISSED' | 'ALL';

export default function OwnerWarnings() {
  const qc = useQueryClient();
  const [filter, setFilter] = useState<Filter>('ACTIVE');

  const { data, isLoading, error } = useQuery({
    queryKey: ['owner', 'warnings'],
    queryFn: async () => (await api.get('/owner/warnings')).data.data as Warning[],
  });

  const scan = useMutation({
    mutationFn: async () => (await api.post('/owner/warnings/scan')).data.data,
    onSuccess: () => qc.invalidateQueries({ queryKey: ['owner', 'warnings'] }),
  });
  const setStatus = useMutation({
    mutationFn: async (b: { id: string; status: string }) =>
      (await api.patch(`/owner/warnings/${b.id}/status`, { status: b.status })).data,
    onSuccess: () => qc.invalidateQueries({ queryKey: ['owner', 'warnings'] }),
  });

  const counts = useMemo(() => {
    const c = { ACTIVE: 0, ACKNOWLEDGED: 0, RESOLVED: 0, DISMISSED: 0, ALL: 0 } as Record<Filter, number>;
    const sev = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 } as Record<string, number>;
    (data ?? []).forEach((w) => {
      c.ALL += 1;
      if (w.status in c) c[w.status as Filter] += 1;
      if (w.status === 'ACTIVE' && w.severity in sev) sev[w.severity] += 1;
    });
    return { c, sev };
  }, [data]);

  const rows = (data ?? []).filter((w) => filter === 'ALL' || w.status === filter);

  if (isLoading) return <Spinner />;
  if (error) return <ErrorBanner message={apiErrorMessage(error)} />;

  return (
    <div>
      <PageHeader
        title="Warnings"
        description="Automatic alerts for overdue rent, expiring leases, missing documents, and delayed tasks. Scanned hourly."
        actions={
          <button className="btn-secondary" onClick={() => scan.mutate()} disabled={scan.isPending}>
            {scan.isPending ? 'Scanning…' : 'Run scan now'}
          </button>
        }
      />
      {scan.data && (
        <p className="mb-4 flex items-center gap-1.5 text-sm text-emerald-600">
          <Icon name="check" size={15} />
          Scan complete — {scan.data.created} new warning(s).
        </p>
      )}

      <SplitLayout
        aside={
          <>
            <RailFilters
              title="Status"
              value={filter}
              onChange={setFilter}
              options={[
                { value: 'ACTIVE', label: 'Active', count: counts.c.ACTIVE },
                { value: 'ACKNOWLEDGED', label: 'Acknowledged', count: counts.c.ACKNOWLEDGED },
                { value: 'RESOLVED', label: 'Resolved', count: counts.c.RESOLVED },
                { value: 'DISMISSED', label: 'Dismissed', count: counts.c.DISMISSED },
                { value: 'ALL', label: 'All', count: counts.c.ALL },
              ]}
            />
            <RailStats
              title="Active by severity"
              rows={[
                { label: 'Critical', value: counts.sev.CRITICAL, tone: 'critical' },
                { label: 'High', value: counts.sev.HIGH, tone: 'critical' },
                { label: 'Medium', value: counts.sev.MEDIUM, tone: 'warning' },
                { label: 'Low', value: counts.sev.LOW },
              ]}
            />
          </>
        }
      >
        {rows.length === 0 ? (
          <EmptyState
            icon="check"
            title={filter === 'ACTIVE' ? 'No active warnings' : 'Nothing here'}
            hint={
              filter === 'ACTIVE'
                ? 'Nothing needs attention. The system re-checks every hour.'
                : undefined
            }
          />
        ) : (
          <div>
            {rows.map((w) => (
              <div
                key={w.id}
                className={`border-b border-slate-100 border-l-2 py-4 pl-4 last:border-b-0 ${
                  w.severity === 'CRITICAL' || w.severity === 'HIGH'
                    ? 'border-l-rose-400'
                    : w.severity === 'MEDIUM'
                      ? 'border-l-amber-400'
                      : 'border-l-slate-200'
                }`}
              >
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="min-w-0">
                    <p className="text-sm font-semibold text-ink-900">
                      {w.title}
                      {w.tenant && <span className="font-normal text-ink-400"> · {w.tenant.fullName}</span>}
                    </p>
                    <p className="mt-0.5 text-sm text-ink-600">{w.message}</p>
                    <p className="mt-1 text-2xs uppercase tracking-wide text-ink-400">
                      {w.type.replaceAll('_', ' ')} · {date(w.createdAt)} · {w.autoGenerated ? 'auto' : 'manual'}
                    </p>
                  </div>
                  <div className="flex flex-wrap items-center gap-2">
                    <Badge>{w.severity}</Badge>
                    <Badge>{w.status}</Badge>
                    {w.status === 'ACTIVE' && (
                      <>
                        <button
                          className="btn-secondary btn-sm"
                          onClick={() => setStatus.mutate({ id: w.id, status: 'RESOLVED' })}
                        >
                          <Icon name="check" size={13} />
                          Resolve
                        </button>
                        <button
                          className="btn-ghost btn-sm"
                          onClick={() => setStatus.mutate({ id: w.id, status: 'DISMISSED' })}
                        >
                          Dismiss
                        </button>
                      </>
                    )}
                  </div>
                </div>
              </div>
            ))}
            {(scan.error || setStatus.error) && (
              <ErrorBanner message={apiErrorMessage(scan.error ?? setStatus.error)} />
            )}
          </div>
        )}
      </SplitLayout>
    </div>
  );
}
